### ISSUE TITLE
Why are you setting -euo pipefile in a lot of the functions and in the top scope?

### ISSUE THREAD

**Issue by matschundbrei** [artemyarulin/monorepo-kubernetes-continuous-delivery#2]
https://github.com/artemyarulin/monorepo-kubernetes-continuous-delivery/blob/09b166c1bb4b4acfce61e61e35dcfe17c8fdf270/.circleci/ci.sh#L30

This might be a stupid question, but why are you doing this and why are you not doing it in all of the functions?

Cheers,
M

**Comment by artemyarulin** [comment]
Hi, not stupid at all! :)

`parallels` execute functions in a new context and not aware about current file execution context. 
`export -f` creates an environment variable with the function body so `parallels` can start it
But function will start in a new context so error handling has to be set there again

```bash
# test.sh
hello() {
   set -euo pipefail 
   echo "hello"
}
export -f hello 
echo "hello" | parallel
```
